#!/bin/bash

#SBATCH --time=00:20:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=4GB

ml TensorFlow/1.10.1-fosscuda-2018a-Python-3.6.4
#ml TensorFlow/1.9.0-foss-2018a-Python-3.6.4-CUDA-9.1.85

python 64alexnet.py
